{% set name = "jina" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af2a64b878db67815ec8e265e1b0a2f56fcc1bee53fac76bb305dabf09753912

build:
  number: 0

outputs:
  - name: jina-core
    build:
      noarch: python
      entry_points:
        - jina = cli:main
        - jinad = daemon:main
      script: python -m pip install . --no-deps -vv
      script_env:
        - JINA_PIP_INSTALL_CORE=1
    test:
      requires:
        - pip
      imports:
        - jina
      commands:
        - pip check
        - jina --version
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __unix
        - python >=3.7
        - docarray >=0.6.3
        - grpcio >=1.33.1
        - numpy
        - packaging >=20.0
        - protobuf >=3.19.1
        - pyyaml >=5.3.1
  - name: jina-perf
    test:
      requires:
        - pip
      imports:
        - jina
      commands:
        - pip check
        - jina --version
    build:
      noarch: python
      entry_points:
        - jina = cli:main
        - jinad = daemon:main
      script: python -m pip install . --no-deps -vv
      script_env:
        - JINA_PIP_INSTALL_PERF=1
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __unix
        - python >=3.7
        - docarray >=0.7.0
        - grpcio >=1.33.1
        - lz4 <3.1.2
        - numpy
        - packaging >=20.0
        - protobuf >=3.19.1
        - python-kubernetes >=18.20.0
        - pyyaml >=5.3.1
        - uvloop
  - name: jina
    test:
      requires:
        - pip
      imports:
        - jina
      commands:
        - pip check
        - jina --version
    build:
      noarch: python
      entry_points:
        - jina = cli:main
        - jinad = daemon:main
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __unix
        - python >=3.7
        - aiofiles
        - aiohttp
        - aiostream
        - cryptography
        - docarray >=0.6.3
        - docker-py
        - fastapi
        - filelock
        - grpcio >=1.33.1
        - lz4 <3.1.2
        - numpy
        - packaging >=20.0
        - pathspec
        - protobuf >=3.19.1
        - pydantic
        - python-kubernetes >=18.20.0
        - python-multipart
        - pyyaml >=5.3.1
        - requests
        - rich
        - uvicorn >=0.14.0,<=0.16.0
        - uvloop
        - websockets

about:
  home: https://github.com/jina-ai/jina/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Jina is the cloud-native neural search framework for any kind of data
  doc_url: https://docs.jina.ai

extra:
  recipe-maintainers:
    - tadejsv
    - JoanFM
    - nan-wang
    - hanxiao
  feedstock-name: jina
