{% set name = "jina" %}
{% set version = "3.13.2" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24e26d8841715b4157b42cc58fe39716cf083bb0c7018e9d9a4a5d913ae6d73a

build:
  number: 0

outputs:
  - name: jina-core
    build:
      noarch: python
      entry_points:
        - jina = cli:main
      script: python -m pip install . --no-deps -vv
      script_env:
        - JINA_PIP_INSTALL_CORE=1
    test:
      requires:
        - pip
      imports:
        - jina
      commands:
        - pip check
        - jina --version
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __unix
        - python >=3.7
        - docarray >=0.16.4
        - grpcio >=1.46.0,<1.48.1
        - grpcio-health-checking >=1.46.0,<1.48.1
        - grpcio-reflection >=1.46.0,<1.48.1
        - jina-hubble-sdk >=0.30.4
        - numpy
        - opentelemetry-api >=1.12.0
        - opentelemetry-instrumentation-grpc >=0.35b0
        - packaging >=20.0
        - protobuf >=3.19.0
        - pyyaml >=5.3.1
  - name: jina-perf
    test:
      requires:
        - pip
      imports:
        - jina
      commands:
        - pip check
        - jina --version
    build:
      noarch: python
      entry_points:
        - jina = cli:main
      script: python -m pip install . --no-deps -vv
      script_env:
        - JINA_PIP_INSTALL_PERF=1
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __unix
        - python >=3.7
        - docarray >=0.16.4
        - grpcio >=1.46.0,<1.48.1
        - grpcio-health-checking >=1.46.0,<1.48.1
        - grpcio-reflection >=1.46.0,<1.48.1
        - jina-hubble-sdk >=0.30.4
        - numpy
        - opentelemetry-api >=1.12.0
        - opentelemetry-exporter-otlp >=1.12.0
        - opentelemetry-instrumentation-aiohttp-client >=0.33b0
        - opentelemetry-instrumentation-fastapi >=0.33b0
        - opentelemetry-instrumentation-grpc >=0.35b0
        - opentelemetry-sdk >=1.14.0
        - packaging >=20.0
        - prometheus_client >=0.12.0
        - protobuf >=3.19.0
        - pyyaml >=5.3.1
        - uvloop
  - name: jina
    test:
      requires:
        - pip
      imports:
        - jina
      commands:
        - pip check
        - jina --version
    build:
      noarch: python
      entry_points:
        - jina = cli:main
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __unix
        - python >=3.7
        - aiofiles
        - aiohttp
        - aiostream
        - docarray >=0.16.4
        - docker-py
        - fastapi >=0.76.0
        - filelock
        - grpcio >=1.46.0,<1.48.1
        - grpcio-health-checking >=1.46.0,<1.48.1
        - grpcio-reflection >=1.46.0,<1.48.1
        - jina-hubble-sdk >=0.30.4
        - numpy
        - opentelemetry-api >=1.12.0
        - opentelemetry-exporter-otlp >=1.12.0
        - opentelemetry-instrumentation-aiohttp-client >=0.33b0
        - opentelemetry-instrumentation-fastapi >=0.33b0
        - opentelemetry-instrumentation-grpc >=0.35b0
        - opentelemetry-sdk >=1.14.0
        - packaging >=20.0
        - pathspec
        - prometheus_client >=0.12.0
        - protobuf >=3.19.0
        - pydantic
        - python-multipart
        - pyyaml >=5.3.1
        - requests
        - uvicorn
        - uvloop
        - websockets

about:
  home: https://github.com/jina-ai/jina/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Build multimodal AI services via cloud native technologies \xB7 Neural Search \xB7 Generative AI \xB7 Cloud Native"
  doc_url: https://docs.jina.ai

extra:
  recipe-maintainers:
    - JoanFM
    - nan-wang
    - hanxiao
  feedstock-name: jina
