{% set name = "jina" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbafd7db138bf371b8d0da9e8de5ccef4297033145a040c890d4aa9146021d7b

build:
  number: 0

outputs:
  - name: jina-core
    build:
      noarch: python
      entry_points:
        - jina = jina_cli:main
      script: python -m pip install . --no-deps -vv
      script_env:
        - JINA_PIP_INSTALL_CORE=1
    test:
      requires:
        - pip
      imports:
        - jina
      commands:
        - pip check
        - jina --version
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __unix
        - python >=3.7
        - docarray >=0.13.14
        - grpcio >=1.46.0
        - grpcio-health-checking >=1.46.0
        - grpcio-reflection >=1.46.0
        - numpy
        - packaging >=20.0
        - protobuf >=3.19.1,<=3.20.1
        - pyyaml >=5.3.1
  - name: jina-perf
    test:
      requires:
        - pip
      imports:
        - jina
      commands:
        - pip check
        - jina --version
    build:
      noarch: python
      entry_points:
        - jina = jina_cli:main
      script: python -m pip install . --no-deps -vv
      script_env:
        - JINA_PIP_INSTALL_PERF=1
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __unix
        - python >=3.7
        - docarray >=0.13.14
        - grpcio >=1.46.0
        - grpcio-health-checking >=1.46.0
        - grpcio-reflection >=1.46.0
        - numpy
        - packaging >=20.0
        - prometheus_client
        - protobuf >=3.19.1,<=3.20.1
        - pyyaml >=5.3.1
        - uvloop
  - name: jina
    test:
      requires:
        - pip
      imports:
        - jina
      commands:
        - pip check
        - jina --version
    build:
      noarch: python
      entry_points:
        - jina = jina_cli:main
      script: python -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __unix
        - python >=3.7
        - aiofiles
        - aiohttp
        - aiostream
        - cryptography
        - docarray >=0.13.14
        - docker-py
        - fastapi >=0.76.0
        - filelock
        - grpcio >=1.46.0
        - grpcio-health-checking >=1.46.0
        - grpcio-reflection >=1.46.0
        - numpy
        - packaging >=20.0
        - pathspec
        - prometheus_client
        - protobuf >=3.19.1,<=3.20.1
        - pydantic
        - python-multipart
        - pyyaml >=5.3.1
        - requests
        - uvicorn
        - uvloop
        - websockets

about:
  home: https://github.com/jina-ai/jina/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Build cross-modal and multi-modal applications on the cloud
  doc_url: https://docs.jina.ai

extra:
  recipe-maintainers:
    - JoanFM
    - nan-wang
    - hanxiao
  feedstock-name: jina
